codecov:
  branch: master
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "build"
  - "host-app"
  - "images"
  - "inbox-ui-tests-app"
  - "misc"
  - "sample-apps"
  - "scripts"
  - "swift-sdk/Internal/Dwifft"
  - "tests"
  - "ui-tests-app"