platform :ios, '11.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
swift_version = '4.0'

target 'objc-sample-app' do
  pod 'Iterable-iOS-SDK', :path => '../../../swift-sdk'
end

target 'objc-sample-app-notification-extension' do
  pod 'Iterable-iOS-AppExtensions', :path => '../../../swift-sdk'
end
