platform :ios, '11.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'swift-sample-app' do
  pod 'IterableSDK', :path => '../../../swift-sdk'
end

target 'swift-sample-app-notification-extension' do
  pod 'IterableAppExtensions', :path => '../../../swift-sdk'
end
