name: Build and test iOS Sample App on Browserstack
on: pull_request

jobs:
  run-ios-browserstack:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
      - run: brew install xcodesorg/made/xcodes

      - name: fastlane build swift-sample-app
        run: bundle exec fastlane build_for_browserstack

      - name: upload swift-sample-app .ipa to browserstack
        id: upload_ipa
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api-cloud.browserstack.com/app-automate/xcuitest/v2/app"
          method: "POST"
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          password: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          files: '{ "file": ${{ github.workspace }}/build-swift-sample-app/swift-sample-app.ipa", "custom_id": "swift-sample-app" }'

      - name: get browserstack app_url
        id: get_app_url
        run: |
          bs_app_url=${{ fromJson(steps.upload_ipa.outputs.response).app_url }}
          echo "::set-output name=app_url::$bs_app_url"

      - name: upload test suite .zip to browserstack
        id: upload_test_zip
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api-cloud.browserstack.com/app-automate/xcuitest/v2/test-suite"
          method: "POST"
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          password: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          files: '{ "file": ${{ github.workspace }}/build-swift-sample-app/swift-sample-app-ui-test.zip", "custom_id": "swift-sample-app-ui-test" }'

      - name: get browserstack test_suite_url
        id: get_test_suite_url
        run: |
          bs_test_suite_url=${{ fromJson(steps.upload_test_zip.outputs.response).test_suite_url }}
          echo "::set-output name=test_suite_url::$bs_test_suite_url"

      - name: execute test suite on browserstack
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api-cloud.browserstack.com/app-automate/xcuitest/v2/build"
          method: "POST"
          username: "justinyu_cIqvyB"
          password: "TszLVeLKEjzwXpVUSB48"
          data: "${{ steps.get_app_url.app_url }},${{ steps.get_test_suite_url.test_suite_url }}"
          file: "${{ github.workspace }}/build-swift-sample-app/swift-sample-app-ui-test.zip"
          customHeaders: '{"Content-Type": "application/json"}'
