name: Build, test and send coverage for SDK

on: [push]

# build
# run tests
# send out coverage reports

jobs:
  # build:
  #   runs-on: macos-latest
  #   steps:


  test:
    # needs: build
    runs-on: macos-latest
    steps:
    - name: CocoaPods Action
      uses: ty0x2333/cocoapods-action@0.2.0
      with:
        additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'

  # coverage:
    # needs: test
    # runs-on: macos-latest
