name: Test + Lint + Report

on: [push]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Run unit tests
      run: xcodebuild test -workspace swift-sdk.xcworkspace -scheme swift-sdk -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone Xs' -enableCodeCoverage YES

  # lint:
  #   # needs: test
  #   runs-on: macos-latest
  #   steps:
  #   - name: CocoaPods library lint action
  #     uses: ty0x2333/cocoapods-action@0.2.0
  #     with:
  #       workspace: swift-sdk
  #       additional_build_params: -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0'

  # coverage:
    # needs: lint
    # runs-on: macos-latest
