//
//  Created by Tapash Majumder on 7/22/20.
//  Copyright © 2020 Iterable. All rights reserved.
//

/// This class mirrors what is automatically generated by Xcode.

import Foundation
import CoreData

@objc(IterableTaskManagedObject)
public class IterableTaskManagedObject: NSManagedObject {
}

extension IterableTaskManagedObject {
    @nonobjc public class func fetchRequest() -> NSFetchRequest<IterableTaskManagedObject> {
        return NSFetchRequest<IterableTaskManagedObject>(entityName: PersistenceConst.EntityName.task)
    }

    @NSManaged public var attempts: Int64
    @NSManaged public var created: Date?
    @NSManaged public var data: Data?
    @NSManaged public var id: String?
    @NSManaged public var lastAttempt: Date?
    @NSManaged public var modified: Date?
    @NSManaged public var processing: Bool
    @NSManaged public var processor: String?
    @NSManaged public var scheduleTime: Date?
}
